pixelCur = (
        "XXXXXX                  ",
        "XXXXXX                  ",
        "XX....XX                ",
        "XX....XX                ",
        "XX......XXXX            ",
        "XX......XXXX            ",
        "  XX........XXXX        ",
        "  XX........XXXX        ",
        "    XX..........XXXX    ",
        "    XX..........XXXX    ",
        "    XX..............XX  ",
        "    XX..............XX  ",
        "      XX..........XX    ",
        "      XX..........XX    ",
        "      XX..........XX    ",
        "      XX..........XX    ",
        "        XX........XXXX  ",
        "        XX........XXXX  ",
        "        XX..XXXXXX..XX  ",
        "        XX..XXXXXX..XX  ",
        "          XX    XXXXXX  ",
        "          XX    XXXXXX  ",
        "                        ",
        "                        "
    )

pixelCur2 = (
        "XXXX            ",
        "XXXX            ",
        "XX..XX          ",
        "XX..XX          ",
        "XX....XX        ",
        "XX....XX        ",
        "XX......XX      ",
        "XX......XX      ",
        "XX........XX    ",
        "XX........XX    ",
        "  XXXX..XX      ",
        "  XXXX..XX      ",
        "      XX..XX    ",
        "      XX..XX    ",
        "        XXXX    ",
        "        XXXX    "
    )

pixelCur3 = (
        "XXXX                    ",
        "XXXX                    ",
        "XX..XX                  ",
        "XX..XX                  ",
        "XX....XX                ",
        "XX....XX                ",
        "XX......XX              ",
        "XX......XX              ",
        "XX........XX            ",
        "XX........XX            ",
        "XX..........XX          ",
        "XX..........XX          ",
        "  XXXX..XXXX            ",
        "  XXXX..XXXX            ",
        "      XX..XX            ",
        "      XX..XX            ",
        "        XX..XX          ",
        "        XX..XX          ",
        "          XXXX          ",
        "          XXXX          ",
        "                        ",
        "                        ",
        "                        ",
        "                        "
    )

pixelCur4 = (
        "                        ",
        "                        ",
        "XXXX                    ",
        "XXXX                    ",
        "XX..XX                  ",
        "XX..XX                  ",
        "XX....XX                ",
        "XX....XX                ",
        "  XX....XX              ",
        "  XX....XX              ",
        "  XX......XX            ",
        "  XX......XX            ",
        "    XXXX..XXXX          ",
        "    XXXX..XXXX          ",
        "        XX..XX          ",
        "        XX..XX          ",
        "          XX..XX        ",
        "          XX..XX        ",
        "            XXXX        ",
        "            XXXX        ",
        "                        ",
        "                        ",
        "                        ",
        "                        "
    )

pixelCur5 = (
        "XXXX                    ",
        "XXXX                    ",
        "XX..XX                  ",
        "XX..XX                  ",
        "XX....XX                ",
        "XX....XX                ",
        "XX......XX              ",
        "XX......XX              ",
        "  XX......XX            ",
        "  XX......XX            ",
        "  XX........XX          ",
        "  XX........XX          ",
        "    XX..XX              ",
        "    XX..XX              ",
        "      XX..XX            ",
        "      XX..XX            ",
        "        XX..XX          ",
        "        XX..XX          ",
        "          XXXX          ",
        "          XXXX          ",
        "                        ",
        "                        ",
        "                        ",
        "                        "
    )

pixelHand = (
        "        XXXXXX          ",
        "        XXXXXX          ",
        "    XXXXXX..XXXXXX      ",
        "    XXXXXX..XXXXXX      ",
        "    XX..XX..XX..XX      ",
        "    XX..XX..XX..XX      ",
        "    XX..XX..XX..XXXXXX  ",
        "    XX..XX..XX..XXXXXX  ",
        "XXXXXX..XX..XX..XX..XX  ",
        "XXXXXX..XX..XX..XX..XX  ",
        "XX..XX..........XX..XX  ",
        "XX..XX..........XX..XX  ",
        "XX..XX..............XX  ",
        "XX..XX..............XX  ",
        "XX..................XX  ",
        "XX..................XX  ",
        "  XX..............XX    ",
        "  XX..............XX    ",
        "  XX..............XX    ",
        "  XX..............XX    ",
        "    XXXXXXXXXXXXXX      ",
        "    XXXXXXXXXXXXXX      ",
        "                        ",
        "                        "
    )

pixel_sizer = (
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        "
    )

pixelDot = (
        "XXXXXXXX",
        "XXXXXXXX",
        "XX....XX",
        "XX....XX",
        "XX....XX",
        "XX....XX",
        "XXXXXXXX",
        "XXXXXXXX"
    )